# Generated by Django 5.1.15 on 2026-06-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_old_job_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aws_face_id',
            field=models.CharField(blank=True, help_text='Identificador asignado por AWS Rekognition al indexar la foto.', max_length=64, verbose_name='AWS face ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='face_indexed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rostro indexado en'),
        ),
    ]
