# Generated by Django 5.1.15 on 2026-07-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_aws_face_id_user_face_indexed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='users/signatures/', verbose_name='Firma'),
        ),
    ]
