# Generated by Django 5.1.15 on 2026-07-06 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(blank=True, choices=[('EJECUTOR', 'Ejecutor'), ('COORDINADOR', 'Coordinador'), ('ADMINISTRADOR', 'Administrador')], help_text='Rol de acceso (RBAC) para navegación y permisos. Independiente del perfil ocupacional: se sugiere un valor según `job_profile` al crear/editar el usuario, pero es editable por un Administrador. Nulo = pendiente de asignación explícita.', max_length=20, null=True, verbose_name='Rol de acceso'),
        ),
        migrations.AddField(
            model_name='user',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='Coordinador o Administrador responsable de este usuario. Se usa para filtrar datos por equipo (Certificados, Gamificación) cuando el rol del supervisor es Coordinador.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipo', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor'),
        ),
    ]
