# Generated by Django 5.1.15 on 2026-07-22 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_backfill_user_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='aws_face_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='face_indexed_at',
        ),
    ]
