# Generated by Django 5.1.15 on 2026-08-25 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_orphaned_face_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(blank=True, choices=[('EJECUTOR', 'Ejecutor'), ('COORDINADOR', 'Coordinador'), ('ADMINISTRADOR', 'Administrador'), ('TESORERIA', 'Tesorería')], help_text='Rol de acceso (RBAC) para navegación y permisos. Independiente del perfil ocupacional: se sugiere un valor según `job_profile` al crear/editar el usuario, pero es editable por un Administrador. Nulo = pendiente de asignación explícita.', max_length=20, null=True, verbose_name='Rol de acceso'),
        ),
    ]
