# Generated by Django 5.1.15 on 2026-07-30 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='n_meses',
            field=models.PositiveSmallIntegerField(default=1, help_text='Cuantos meses de suscripcion cubre este pago (monto / precio del plan al momento del pago).', verbose_name='Meses cubiertos'),
        ),
    ]
