# Generated by Django 5.1.15 on 2026-04-29 20:03

import re
from django.db import migrations


def convert_youtube_urls(apps, schema_editor):
    """Convierte URLs de YouTube normales a URLs de embed."""
    Lesson = apps.get_model('courses', 'Lesson')

    def convert_url(url):
        if not url:
            return url
        patterns = [
            r'youtube\.com/watch\?v=([a-zA-Z0-9_-]{11})',
            r'youtu\.be/([a-zA-Z0-9_-]{11})',
            r'youtube\.com/embed/([a-zA-Z0-9_-]{11})',
            r'youtube-nocookie\.com/embed/([a-zA-Z0-9_-]{11})',
        ]
        for pattern in patterns:
            match = re.search(pattern, url)
            if match:
                video_id = match.group(1)
                return f'https://www.youtube.com/embed/{video_id}'
        return url

    for lesson in Lesson.objects.filter(lesson_type='video').exclude(video_url=''):
        converted = convert_url(lesson.video_url)
        if converted != lesson.video_url:
            lesson.video_url = converted
            lesson.save(update_fields=['video_url'])


def reverse_convert(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_add_signatures'),
    ]

    operations = [
        migrations.RunPython(convert_youtube_urls, reverse_convert),
    ]
