# Generated by Django 5.1.15 on 2026-05-05 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_convert_youtube_urls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF'), ('scorm', 'SCORM'), ('interactive', 'Interactivo'), ('audio', 'Audio'), ('quiz', 'Quiz'), ('text', 'Texto'), ('presential', 'Presencial'), ('attendance', 'Asistencia')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='AttendanceSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_image', models.ImageField(upload_to='signatures/%Y/%m/', verbose_name='Imagen de firma')),
                ('signature_type', models.CharField(choices=[('student', 'Firma de Estudiante'), ('instructor', 'Firma del Instructor')], default='student', max_length=20, verbose_name='Tipo de firma')),
                ('signed_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora de firma')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('device_info', models.JSONField(blank=True, default=dict, verbose_name='Información del dispositivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_attendances', to=settings.AUTH_USER_MODEL, verbose_name='Instructor asignado')),
                ('lesson', models.ForeignKey(limit_choices_to={'lesson_type': 'attendance'}, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_signatures', to='courses.lesson', verbose_name='Lección')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_signatures', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Firma de Asistencia',
                'verbose_name_plural': 'Firmas de Asistencia',
                'db_table': 'attendance_signatures',
                'ordering': ['-signed_at'],
                'indexes': [models.Index(fields=['lesson', 'user'], name='attendance__lesson__af3a56_idx'), models.Index(fields=['lesson', 'signed_at'], name='attendance__lesson__8a8ab7_idx')],
                'constraints': [models.UniqueConstraint(fields=('lesson', 'user'), name='unique_attendance_signature')],
            },
        ),
    ]
