# Generated by Django 5.1.15 on 2026-06-04 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_lesson_lesson_type_attendancesignature'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, help_text='Solo para lecciones de Asistencia', null=True, verbose_name='Fecha y hora agendada'),
        ),
    ]
