# Generated by Django 5.1.15 on 2026-06-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_remove_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF'), ('scorm', 'SCORM'), ('interactive', 'Interactivo'), ('audio', 'Audio'), ('quiz', 'Evaluación'), ('text', 'Texto'), ('presential', 'Presencial'), ('attendance', 'Asistencia')], max_length=20, verbose_name='Tipo'),
        ),
    ]
