# Generated by Django 5.1.15 on 2026-07-02 07:59
"""SD#48 -- data-fix migration (not a manual post-deploy query).

save_attendance_signature() (apps/courses/views.py) marked
LessonProgress.is_completed=True on signing but never set
progress_percent, so it stayed at its 0.00 default for every attendance
lesson signed before this fix (see the sibling code fix in the same
commit). Rows signed BEFORE this deploy are stuck at is_completed=True /
progress_percent=0.00 forever unless backfilled. RunPython so it ships in
the normal autonomous deploy pipeline (with the E2E gate as safety net)
instead of a manual UPDATE against prod.
"""
from django.db import migrations


def backfill_attendance_progress_percent(apps, schema_editor):
    LessonProgress = apps.get_model("courses", "LessonProgress")
    LessonProgress.objects.filter(
        is_completed=True,
        progress_percent=0,
        lesson__lesson_type="attendance",
    ).update(progress_percent=100)


def noop_reverse(apps, schema_editor):
    # Intentionally irreversible in a destructive sense: we can't tell
    # apart rows that were legitimately 0% (impossible for a completed
    # attendance lesson, but kept as a no-op rather than guessing which
    # rows to revert to 0).
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_remove_category_parent_field'),
    ]

    operations = [
        migrations.RunPython(
            backfill_attendance_progress_percent,
            reverse_code=noop_reverse,
        ),
    ]
