# Generated by Django 5.1.15 on 2026-07-20 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_backfill_attendance_progress_percent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('charla', 'Charla'), ('capacitacion', 'Capacitación'), ('simulacro', 'Simulacro'), ('socializacion', 'Socialización'), ('otra', 'Otra')], default='', max_length=20, verbose_name='Tipo de actividad'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(blank=True, help_text='Instructor responsable de la actividad (firma en el reporte de asistencia)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_as_instructor', to=settings.AUTH_USER_MODEL, verbose_name='Instructor'),
        ),
        migrations.AddField(
            model_name='course',
            name='project_name',
            field=models.CharField(blank=True, default='', help_text='Proyecto/obra al que pertenece la actividad (formato FT-HSEQ-60)', max_length=200, verbose_name='Proyecto'),
        ),
    ]
