# Generated by Django 5.1.15 on 2026-07-29 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_course_attendance_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Identifica la convocatoria (ej: 'Turno X', 'Cuadrilla norte')", max_length=150, verbose_name='Nombre de la programación')),
                ('suggested_end_date', models.DateField(blank=True, help_text='Fecha sugerida, NO un límite duro: pasada la fecha el convocado sigue pudiendo completar el curso.', null=True, verbose_name='Fecha de finalización sugerida')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='courses.course', verbose_name='Curso')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_schedules_created', to=settings.AUTH_USER_MODEL, verbose_name='Creada por')),
                ('responsable', models.ForeignKey(blank=True, help_text='Su firma de perfil es la que aparece en el reporte de asistencia de esta programación. Al reasignar, la firma pasa a ser la del nuevo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_schedules_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Programación de curso',
                'verbose_name_plural': 'Programaciones de curso',
                'db_table': 'course_schedules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('user', 'Persona específica'), ('profile', 'Perfil ocupacional'), ('position', 'Cargo')], default='user', max_length=20, verbose_name='Origen de la convocatoria')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(blank=True, help_text='Inscripción reusada o creada al convocar.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_assignments', to='courses.enrollment', verbose_name='Inscripción')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.courseschedule', verbose_name='Programación')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_schedule_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Convocado')),
            ],
            options={
                'verbose_name': 'Convocado a programación',
                'verbose_name_plural': 'Convocados a programación',
                'db_table': 'schedule_assignments',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.AddIndex(
            model_name='courseschedule',
            index=models.Index(fields=['course', '-created_at'], name='course_sche_course__65f3df_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleassignment',
            index=models.Index(fields=['schedule'], name='schedule_as_schedul_a29364_idx'),
        ),
        migrations.AddConstraint(
            model_name='scheduleassignment',
            constraint=models.UniqueConstraint(fields=('schedule', 'user'), name='unique_schedule_assignment'),
        ),
    ]
