# Generated by Django 5.1.15 on 2026-07-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_courseschedule_scheduleassignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseschedule',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('charla', 'Charla'), ('capacitacion', 'Capacitación'), ('simulacro', 'Simulacro'), ('socializacion', 'Socialización'), ('otra', 'Otra')], default='', help_text='Tipo de actividad de ESTA convocatoria (reusa las opciones del curso). Opcional -- no hereda automáticamente el del curso.', max_length=20, verbose_name='Tipo de actividad'),
        ),
    ]
