# Generated by Django 5.1.15 on 2026-06-04 02:24

from decimal import Decimal

from django.db import migrations, models

import apps.core.validators


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0003_alter_assessment_passing_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="passing_score",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("80.00"),
                help_text="Porcentaje mínimo para aprobar",
                max_digits=5,
                validators=[apps.core.validators.validate_percentage],
                verbose_name="Puntaje mínimo (%)",
            ),
        ),
        migrations.AlterField(
            model_name="assessmentattempt",
            name="points_earned",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=5,
                verbose_name="Puntos obtenidos",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="points",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("1.00"), max_digits=5, verbose_name="Puntos"
            ),
        ),
    ]
