# Generated by Django 5.1.15 on 2026-06-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_decimal_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='assessment_type',
            field=models.CharField(choices=[('quiz', 'Evaluación'), ('exam', 'Examen'), ('practice', 'Práctica'), ('survey', 'Encuesta')], default='quiz', max_length=20, verbose_name='Tipo'),
        ),
    ]
