# Generated by Django 5.1.15 on 2026-07-06 17:10

from django.db import migrations, models


def backfill_max_attempts_ilimitado(apps, schema_editor):
    """SD#57.2: 'todas ilimitadas' incluye el historico (decision de Miguel) --
    pasa TODAS las evaluaciones YA EXISTENTES a max_attempts=0. Idempotente
    (el WHERE excluye las que ya estan en 0, incl. reintentos del deploy)."""
    Assessment = apps.get_model("assessments", "Assessment")
    Assessment.objects.exclude(max_attempts=0).update(max_attempts=0)


def noop_reverse(apps, schema_editor):
    # No reversible por diseño: no hay forma de reconstruir los valores
    # individuales de max_attempts previos al backfill (no se guardaron).
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_alter_assessment_assessment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='max_attempts',
            field=models.PositiveIntegerField(default=0, help_text='0 = intentos ilimitados', verbose_name='Intentos máximos'),
        ),
        migrations.RunPython(backfill_max_attempts_ilimitado, noop_reverse),
    ]
