# Generated by Django 5.1.15 on 2026-08-09 15:16

import apps.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_backfill_matching_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='passing_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.50'), help_text='Puntaje mínimo para aprobar (escala 0-5)', max_digits=5, validators=[apps.core.validators.validate_0_5_scale], verbose_name='Puntaje mínimo'),
        ),
        migrations.AlterField(
            model_name='assessmentattempt',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Puntaje'),
        ),
    ]
