# Generated by Django 5.1.15 on 2026-09-06 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0009_convert_scores_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='modality',
            field=models.CharField(choices=[('oral', 'Oral'), ('written', 'Escrita'), ('other', 'Otra')], default='other', help_text='Forma en que se presenta la evaluación.', max_length=20, verbose_name='Modalidad'),
        ),
    ]
