# Generated by Django 5.1.15 on 2026-04-16 15:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría de Equipo',
                'verbose_name_plural': 'Categorías de Equipos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('minor', 'Menor'), ('major', 'Mayor'), ('critical', 'Crítica')], max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='findings/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hallazgo',
                'verbose_name_plural': 'Hallazgos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('acquisition_date', models.DateField()),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inspections.equipmentcategory')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CorrectiveAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Progreso'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='pending', max_length=20)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrective_actions', to=settings.AUTH_USER_MODEL)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrective_actions', to='inspections.finding')),
            ],
            options={
                'verbose_name': 'Acción Correctiva',
                'verbose_name_plural': 'Acciones Correctivas',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=50, unique=True)),
                ('inspection_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('scheduled_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Proceso'), ('completed', 'Completada'), ('rejected', 'Rechazada')], default='pending', max_length=20)),
                ('criticality', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('critical', 'Crítica')], default='low', max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('observations', models.TextField(blank=True)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='inspections.equipment')),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections_conducted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inspección',
                'verbose_name_plural': 'Inspecciones',
                'ordering': ['-inspection_date'],
            },
        ),
        migrations.AddField(
            model_name='finding',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='inspections.inspection'),
        ),
        migrations.CreateModel(
            name='InspectionChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operational_condition', models.BooleanField(blank=True, null=True)),
                ('safety_devices_ok', models.BooleanField(blank=True, null=True)),
                ('maintenance_current', models.BooleanField(blank=True, null=True)),
                ('documentation_complete', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='inspections.inspection')),
            ],
            options={
                'verbose_name': 'Checklist de Inspección',
                'verbose_name_plural': 'Checklists de Inspección',
            },
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['folio'], name='inspections_folio_84f1b2_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['equipment', 'inspection_date'], name='inspections_equipme_83e0e3_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['status'], name='inspections_status_094ca4_idx'),
        ),
    ]
