# Generated by Django 5.1.15 on 2026-07-27 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_reportante', models.CharField(max_length=120, verbose_name='Nombre del reportante')),
                ('asunto', models.CharField(max_length=200, verbose_name='Asunto')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('github_issue_number', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Número de issue en GitHub')),
                ('github_url', models.URLField(blank=True, verbose_name='URL del issue en GitHub')),
                ('sincronizado_github', models.BooleanField(default=False, verbose_name='Sincronizado con GitHub')),
                ('error_sincronizacion', models.TextField(blank=True, verbose_name='Error de sincronización')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ticket de feedback',
                'verbose_name_plural': 'Tickets de feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='feedback/adjuntos/%Y/%m/', verbose_name='Imagen')),
                ('nombre_original', models.CharField(blank=True, max_length=255, verbose_name='Nombre original del archivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='feedback.feedbackticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Adjunto de feedback',
                'verbose_name_plural': 'Adjuntos de feedback',
                'ordering': ['created_at'],
            },
        ),
    ]
