# Generated by Django 5.1.15 on 2026-07-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_portal_v2_media_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackattachment',
            name='transcripcion_ia',
            field=models.TextField(blank=True, default='', help_text='Texto generado por Gemini (apps.feedback.gemini_client) a partir del contenido del adjunto — issue #71 ronda 3. Vacío si GEMINI_API_KEY no está configurado o la transcripción falló (best-effort, nunca bloquea la creación del ticket).', verbose_name='Transcripción IA'),
        ),
    ]
