# Generated by Django 5.1.15 on 2026-08-06 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_feedbackattachment_transcripcion_ia'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackticket',
            name='ip_reportante',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP del reportante'),
        ),
    ]
