# Generated by Django 5.1.15 on 2026-06-04 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True, verbose_name='fecha')),
                ('check_in', models.TimeField(blank=True, null=True, verbose_name='entrada')),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='salida')),
                ('hours_worked', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='horas trabajadas')),
                ('is_absent', models.BooleanField(default=False, verbose_name='ausente')),
                ('absence_reason', models.CharField(blank=True, max_length=200, verbose_name='motivo ausencia')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_registered', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Registro de asistencia',
                'verbose_name_plural': 'Registros de asistencia',
                'ordering': ['-date', 'user'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='FaceCheckEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('check_in', 'Entrada'), ('check_out', 'Salida')], max_length=10, verbose_name='tipo')),
                ('status', models.CharField(choices=[('matched', 'Identificado'), ('low_confidence', 'Confianza baja'), ('no_match', 'Sin coincidencia'), ('no_face', 'Sin rostro detectado'), ('error', 'Error del servicio')], max_length=20, verbose_name='estado')),
                ('selfie', models.ImageField(upload_to='attendance/selfies/%Y/%m/%d/', verbose_name='selfie')),
                ('similarity', models.DecimalField(blank=True, decimal_places=2, help_text='Similaridad con la foto de referencia según Rekognition.', max_digits=5, null=True, verbose_name='similitud (%)')),
                ('aws_face_id', models.CharField(blank=True, max_length=64, verbose_name='AWS face ID detectado')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='latitud')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='longitud')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='user agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('error_message', models.CharField(blank=True, max_length=255, verbose_name='mensaje de error')),
                ('attendance_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_events', to='attendance.attendancerecord', verbose_name='registro asistencia')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_events', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Evento de reconocimiento facial',
                'verbose_name_plural': 'Eventos de reconocimiento facial',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='attendance__created_c60c32_idx'), models.Index(fields=['status', '-created_at'], name='attendance__status_36f2ef_idx')],
            },
        ),
    ]
