# Generated by Django 5.1.15 on 2026-07-10 04:31

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0002_alter_certificate_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatetemplate',
            name='template_file',
            field=models.FileField(blank=True, help_text='Archivo HTML/PDF de la plantilla (opcional -- una plantilla puede definir solo logo/firma y usar la plantilla HTML por defecto del sistema, SD#59 A2)', upload_to='certificates/templates/', validators=[apps.core.validators.FileExtensionValidator(['html', 'htm', 'pdf'], message='Las plantillas de certificado deben ser HTML o PDF.')], verbose_name='Archivo de plantilla'),
        ),
    ]
